### ISSUE TITLE
Find interesting place

### ISSUE THREAD

**Issue by tanya-tymkiv** [maxSlkk/DVVSPractice4#10]

**Comment by dganushkeevych** [comment]
[https://www.thecrazytourist.com/25-best-things-to-do-in-london/
[dvvs.docx](https://github.com/maxSlkk/DVVSPractice4/files/4496403/dvvs.docx)
](url)

**Comment by dganushkeevych** [comment]
[https://www.thecrazytourist.com/25-best-things-to-do-in-london/](url)

**Comment by dganushkeevych** [comment]
[dvvs.docx](https://github.com/maxSlkk/DVVSPractice4/files/4496408/dvvs.docx)

**Comment by tanya-tymkiv** [comment]
![image](https://user-images.githubusercontent.com/62881956/79634526-95a40d00-8173-11ea-8d85-cbfeda0de108.png)

**Comment by maxSlkk** [comment]
COOOL

**Comment by tanya-tymkiv** [comment]
I found interesting places for us
