### ISSUE TITLE
hotel

### ISSUE THREAD

**Issue by dganushkeevych** [maxSlkk/DVVSPractice4#13]

**Comment by Slayrak** [comment]
https://www.booking.com/hotel/gb/the-connaught-mayfair.uk.html?aid=346426&label=london-hotels&sid=061797786219b7c6c9878cbe141ba9d5&all_sr_blocks=3805501_203273156_0_2_0%2C3805501_203273156_0_2_0&checkin=2020-07-22&checkout=2020-07-26&dest_id=-2601889&dest_type=city&group_adults=4&group_children=0&hapos=1&highlighted_blocks=3805501_203273156_0_2_0%2C3805501_203273156_0_2_0&hpos=1&no_rooms=1&origin=hp&req_adults=4&req_children=0&room1=A%2CA%2CA%2CA&sr_order=popularity&sr_pri_blocks=3805501_203273156_0_2_0__264000%2C3805501_203273156_0_2_0__264000&srepoch=1587205080&srpvid=13df486b1354004b&ucfs=1&from=searchresults;hptv=do

**Comment by Slayrak** [comment]
![image](https://user-images.githubusercontent.com/57751436/79635248-955a4080-8178-11ea-8557-bd472b88f882.png)
