### ISSUE TITLE
find place for trip

### ISSUE THREAD

**Issue by dganushkeevych** [maxSlkk/DVVSPractice4#7]

**Comment by dganushkeevych** [comment]
[https://www.google.com/maps/place/%D0%9B%D0%BE%D0%BD%D0%B4%D0%BE%D0%BD,+%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F/data=!4m2!3m1!1s0x47d8a00baf21de75:0x52963a5addd52a99?sa=X&ved=2ahUKEwiqmuaj2_HoAhWs5KYKHboaAmUQ8gEwAHoECAsQAQ](url)

**Comment by maxSlkk** [comment]
London is so expensive place

**Comment by maxSlkk** [comment]
but i like it

**Comment by dganushkeevych** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/47561280/79634718-fe3fb980-8174-11ea-834c-6cbb3a3f9504.png)
