### ISSUE TITLE
buy tickets

### ISSUE THREAD

**Issue by Slayrak** [maxSlkk/DVVSPractice4#9]

**Comment by Slayrak** [comment]
![image](https://user-images.githubusercontent.com/57751436/79634507-786f3e80-8173-11ea-841e-e2ec4ce133d4.png)

**Comment by Slayrak** [comment]
![image](https://user-images.githubusercontent.com/57751436/79634599-195df980-8174-11ea-8f6d-51dd8a9c67c2.png)

**Comment by Slayrak** [comment]
https://book.lot.com/web/lot-airways/flights?id=f0fbd95e0f1d47e187b05147aadbb0b3&utm_medium=metasearch&utm_source=googleflight

**Comment by dganushkeevych** [comment]
Let's buy the cheapest tickets !
